baseURL = 'https://kexar007.github.io/customblog/'
languageCode = 'en-us'
title = "My Minimal Blog"
theme = "minima-bw"


[params]
description = "A minimal black-and-white blog powered by Hugo and minima-bw theme."


[permalinks]
posts = "/posts/:slug/"
